//
//  RemainderViewController.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemainderDisplayLogic: class {
    func displayRemainders(viewModel: Remainder.RemainderData.ViewModel)
}

class RemainderViewController: UITableViewController, RemainderDisplayLogic {
    var interactor: RemainderBusinessLogic?
    var router: (NSObjectProtocol & RemainderRoutingLogic & RemainderDataPassing)?
    lazy var longPressGesture = UILongPressGestureRecognizer(target: self, action: #selector(handleLongPress))
    
    var remainders: [RemainderForm] = []
    var  tappedCellIndex: Int?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = RemainderInteractor()
        let presenter = RemainderPresenter()
        let router = RemainderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    @objc private func handleLongPress(sender: UILongPressGestureRecognizer) {
        if sender.state == .began {
            let touchPoint = sender.location(in: tableView)
            if let indexPath = tableView.indexPathForRow(at: touchPoint) {
                tappedCellIndex = indexPath.row
            }
        }
        showActionSheet()
    }
    
    func showActionSheet() {
        let alert = UIAlertController(title: "", message: "Please Select an Option", preferredStyle: .actionSheet)
        
        alert.addAction(UIAlertAction(title: "Edit", style: .default , handler:{ [weak self] (UIAlertAction)in
            let request = Remainder.RemainderData.Request(remainder: self?.remainders[self!.tappedCellIndex!])
            self?.interactor?.editRemainder(request: request)
            self?.router?.routeToCreateRemander(segue: nil)
        }))
        
        alert.addAction(UIAlertAction(title: "Delete", style: .destructive , handler:{ [weak self] (UIAlertAction)in
            let request = Remainder.RemainderData.Request(remainder: self?.remainders[self!.tappedCellIndex!])
            self?.interactor?.removeRemainder(request: request)
            self?.remainders.remove(at: self!.tappedCellIndex!)
            self?.tableView.reloadData()
        }))
        
        alert.addAction(UIAlertAction(title: "Dismiss", style: .cancel, handler: nil))
        
        self.present(alert, animated: true, completion: {
            print("completion block")
        })
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.addGestureRecognizer(longPressGesture)
        navigationItem.rightBarButtonItems = [
            UIBarButtonItem(image: UIImage(systemName: "doc.fill.badge.plus")?
                                .withTintColor(UIColor.black,
                                               renderingMode: .alwaysOriginal),
                            style: .done, target: self, action: #selector(addRemainder)),
            
        ]
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        getRemainders()
    }
    
    // MARK: Do something
    func getRemainders() {
        let request = Remainder.RemainderData.Request()
        interactor?.fetchRemainderFile(request: request)
    }
    
    @objc func addRemainder() {
        router?.routeToCreateRemander(segue: nil)
    }
    func displayRemainders(viewModel: Remainder.RemainderData.ViewModel) {
        remainders = viewModel.remainders
        tableView.reloadData()
    }
}

extension RemainderViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        remainders.count
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        TableViewConstatns.remainderTableVieCellHeight
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "RemaindetTableViewCell", for: indexPath) as? RemaindetTableViewCell else { return UITableViewCell() }
        cell.configure(remainderData: remainders[indexPath.row])
        return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let request = Remainder.RemainderData.Request(remainder: remainders[indexPath.row])
        interactor?.editRemainder(request: request)
        router?.routeToCreateRemander(segue: nil)
    }
}
