//
//  RemainderWorker.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RemainderWorker {
    
    func getRemaindersFile(directory: String,complition: @escaping ([Data]) -> Void ) {
        var remaindersData: [Data] = []
        let createRemaindeFolderAddress = "\(String(describing: FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.path))/\(directory)"
        guard let fileManegeUrl = URL(string: createRemaindeFolderAddress) else { return }
        let urlArray = try! FileManager.default.contentsOfDirectory(at: fileManegeUrl, includingPropertiesForKeys: nil, options: .skipsHiddenFiles)
        for fileUrl in urlArray {
            do {
                let data = try Data(contentsOf: fileUrl)
                remaindersData.append(data)
            } catch {
                print(error)
            }
        }
        complition(remaindersData)
    }
    
    func deleteRemainderNote(in directory: String, remainderTitle: String) {
        let createRemaindeFolderAddress = "\(String(describing: FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.path))/\(directory)/\(remainderTitle).txt"
        do {
            try FileManager.default.removeItem(atPath: createRemaindeFolderAddress)
        } catch {
            print(error)
        }
    }
    
}
