//
//  RemainderModels.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Remainder
{
  // MARK: Use cases
  
  enum RemainderData {
    struct Request {
        var remainder: RemainderForm?
    }
    struct Response {
        var objects: [Data]?
    }
    struct ViewModel {
        var remainders: [RemainderForm]
    }
  }
}
