//
//  RemainderModels.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Reminder {
    
    // MARK: Use cases
    enum Set {
        struct Request {
            var reminder: ReminderForm
        }
        struct Response {
            var objects: [Data]?
        }
        struct ViewModel {
            var remainders: [ReminderForm]
        }
    }
    
    enum ReminderData {
        struct Request {
            var remainder: ReminderForm?
        }
        struct Response {
            var objects: [Data]?
        }
        struct ViewModel {
            var remainders: [ReminderForm]
        }
    }
}
