//
//  RemainderRouter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ReminderRoutingLogic {
    func routeToCreateReminder(segue: UIStoryboardSegue?)
}

protocol ReminderDataPassing {
    var dataStore: ReminderDataStore? { get }
}

class ReminderRouter: NSObject, ReminderRoutingLogic, ReminderDataPassing {
    
    weak var viewController: ReminderViewController?
    var dataStore: ReminderDataStore?
    
    // MARK: Routing
    func routeToCreateReminder(segue: UIStoryboardSegue?) {
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "CreateRemainderViewController") as? ModifyRemainderViewController else { return }
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    //   MARK: Navigation
    func navigateToSomewhere(source: ReminderViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    //   MARK: Passing data
    func passDataToSomewhere(source: ReminderDataStore, destination: inout ModifyRemainderDataStore) {
        destination.name = source.name
        destination.remainderData = source.remainderData
    }
}
