//
//  RemainderPresenter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReminderPresentationLogic {
    func presentRemainders(response: Reminder.ReminderData.Response)
}

class ReminderPresenter: ReminderPresentationLogic
{
    weak var viewController: ReminderDisplayLogic?
    
    func presentRemainders(response: Reminder.ReminderData.Response) {
        var remainderArray: [ReminderForm] = []
        response.objects!.forEach({ data in
            do {
                let remainder = try JSONDecoder().decode(ReminderForm.self, from: data)
                remainderArray.append(remainder)
            } catch {
                print(error)
            }
        })
        
        let viewModel = Reminder.ReminderData.ViewModel(remainders: remainderArray)
        viewController?.displayRemainders(viewModel: viewModel)
    }
}
