//
//  CreateRemainderModels.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ModifyRemainder {
    
    enum Info {
        struct Request{
            var remainder: ReminderForm
        }
        struct Response{
            var error: Error?
        }
        struct ViewModel {
            var title: AlertTitle
            var massege: String
        }
    }
}
