//
//  CreateRemainderPresenter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRemainderPresentationLogic {
    func presentMessage(response: ModifyRemainder.Info.Response)
}

class ModifyRemainderPresenter: CreateRemainderPresentationLogic {
    weak var viewController: CreateRemainderDisplayLogic?
    
    // MARK: Do something
    
    func presentMessage(response: ModifyRemainder.Info.Response) {
        var message = ""
        if response.error == nil {
            message = "Remainder successfully added"
        } else {
            message = response.error!.localizedDescription
        }
        
        let viewModel = ModifyRemainder.Info.ViewModel(massege: message)
        viewController?.displayMessage(viewModel: viewModel)
    }
}
