//
//  CreateRemainderWorker.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ModifyRemainderWorker {
    func addReminderNote(in directory: String, remainder: RemainderForm, complition: @escaping (Error?) -> Void) {
        let remainderUrl = "\(String(describing: FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.path))/\(directory)"
        guard var url = URL(string: remainderUrl) else { return }
        url.appendPathComponent("\(remainder.title).txt")
        do {
            let data = try JSONEncoder().encode(remainder)
            FileManager.default.createFile(atPath: url.path, contents: data, attributes: nil )
            complition(nil)
        } catch {
            complition(error)
        }
    }
}
