//
//  CreateRemainderInteractor.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRemainderBusinessLogic {
    func addRemainder(request: ModifyRemainder.Info.Request)
}

protocol ModifyRemainderDataStore {
    var name: String { get set }
    var remainderData: RemainderForm? { get set }
}

class ModifyRemainderInteractor: CreateRemainderBusinessLogic, ModifyRemainderDataStore
{
    var presenter: CreateRemainderPresentationLogic?
    var worker: ModifyRemainderWorker?
    var name: String = ""
    var remainderData: RemainderForm?
    // MARK: Do something
    
    func addRemainder(request: ModifyRemainder.Info.Request) {
        worker = ModifyRemainderWorker()
        worker?.addReminderNote(in: name, remainder: request.remainder, complition: { [weak self] error in
            let response = ModifyRemainder.Info.Response(error: error)
            self?.presenter?.presentMessage(response: response)
        })
    }
}
