//
//  CreateRemainderRouter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateRemainderRoutingLogic {
    func routeToRemainderPage(segue: UIStoryboardSegue?)
}

protocol CreateRemainderDataPassing {
    var dataStore: ModifyRemainderDataStore? { get }
}

class ModifyRemainderRouter: NSObject, CreateRemainderRoutingLogic, CreateRemainderDataPassing {
    weak var viewController: ModifyRemainderViewController?
    var dataStore: ModifyRemainderDataStore?
    
    // MARK: Routing
    
    func routeToRemainderPage(segue: UIStoryboardSegue?) {
        navigateToRemainderPage(source: viewController!, destination: UIViewController())
    }
}

// MARK: Navigation

func navigateToRemainderPage(source: ModifyRemainderViewController, destination: UIViewController) {
    source.navigationController?.popViewController(animated: true)
}

// MARK: Passing data

//  func passDataToSomewhere(source: CreateRemainderDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
//}
