//
//  CreateRemainderRouter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/24/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateRemainderRoutingLogic {
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CreateRemainderDataPassing {
  var dataStore: ModifyRemainderDataStore? { get }
}

class ModifyRemainderRouter: NSObject, CreateRemainderRoutingLogic, CreateRemainderDataPassing {
  weak var viewController: ModifyRemainderViewController?
  var dataStore: ModifyRemainderDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?) {
    
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
//  func navigateToSomewhere(source: CreateRemainderViewController, destination: SomewhereViewController)
//  {
//    source.show(destination, sender: nil)
//  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: CreateRemainderDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
//}
