//
//  DirectoryFileModels.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DirectoryFile {

    enum Directory {
        struct Request {}
        struct Response {
            var objects: [String]
        }
        struct ViewModel {
            var fileNames: [String]?
        }
    }

    enum DirectoryInfo {
        struct Request {
            var directoryName: String
        }
        struct Response {
            var error: Error?
        }
        struct ViewModel {
            var error: String?
        }
    }
}
