//
//  DirectoryFileWorker.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DirectoryFileWorker {
    
    func addDirectoryToFileManager(with name: String, complition: @escaping (Error?) -> Void) {
        var url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
        url!.appendPathComponent(name)
        do {
            try FileManager.default.createDirectory(at: url!, withIntermediateDirectories: true)
            complition(nil)
        } catch {
            complition(error)
        }
    }
    
    func getFiles(complition: @escaping ([String]) -> Void ) {
        guard let fileManegeUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else { return }
        
        do {
            let file = try FileManager.default.contentsOfDirectory(atPath: fileManegeUrl.path)
            complition(file)
        } catch  {
            print(error)
        }
    }
}
