//
//  DirectoryFilePresenter.swift
//  MirianMAglakelidze#24
//
//  Created by Admin on 8/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DirectoryFilePresentationLogic {
    func presentErroToString(response: DirectoryFile.DirectoryInfo.Response)
    func presentFileNames(response: DirectoryFile.Directory.Response)
}

class DirectoryFilePresenter: DirectoryFilePresentationLogic {
    
    weak var viewController: DirectoryFileDisplayLogic?
    
    func presentErroToString(response: DirectoryFile.DirectoryInfo.Response) {
        let viewModel = DirectoryFile.DirectoryInfo.ViewModel(error: response.error?.localizedDescription)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentFileNames(response: DirectoryFile.Directory.Response) {
        var fileNames = response.objects
        fileNames.removeAll { $0.uppercased() == ".DS_Store".uppercased() }
        let viewModel = DirectoryFile.Directory.ViewModel(fileNames: fileNames)
        viewController?.displayFiles(viewModel: viewModel)
    }
}
